import './globals.scss';
import { Noto_Sans } from 'next/font/google';
import TanstackProvider from '@/utils/providers/TanstackProvider';
// import { ReactQueryDevtools } from '@tanstack/react-query-devtools';

const noto = Noto_Sans({
  weight: ['400', '700'],
  subsets: ['latin'],
})

export const metadata = {
  title: 'Evermore Style',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${noto.className}`}>
        <TanstackProvider>
          {children}
        {/* <ReactQueryDevtools /> */}
        </TanstackProvider>
      </body>
    </html>
  )
}
